### ISSUE TITLE
Notification down on naas.ai

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/notifications#280]
500 Server Error: Internal Server Error for url: http://naas-notifications:3003/

**Comment by FlorentLvr** [comment]
<img width="608" alt="image" src="https://github.com/jupyter-naas/notifications/assets/48032461/f1f3e433-04aa-4c92-a9d8-5c5e01eec145">

**Comment by Dr0p42** [comment]
Thank you @FlorentLvr for opening this issue.

It seems that we have an issue with Sendgrid credentials. I wanted to check them in Sendgrid but it seems that there is an MFA setup that I do not have



![Image](https://github.com/jupyter-naas/notifications/assets/22365519/65d14baa-7c4c-409f-9620-f6d2d6baf3f0)



Is you @jravenel who is receiving those texts codes ?

**Comment by Dr0p42** [comment]
This is the actual error we are having



![Image](https://github.com/jupyter-naas/notifications/assets/22365519/171fb427-6c58-411d-b494-d12598c4ccc0)

**Comment by Dr0p42** [comment]
Ok it's fixed @FlorentLvr
